// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGvIzIpLureXu35Gtp_PU8cWZJECJhuRQ',
    appId: '1:594510927743:web:30cf149c021f75ede5ec4a',
    messagingSenderId: '594510927743',
    projectId: 'pdm-app-b7cf2',
    authDomain: 'pdm-app-b7cf2.firebaseapp.com',
    storageBucket: 'pdm-app-b7cf2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1CeRBu1cRIV6qcMFOTq-twQTmC5mvMIk',
    appId: '1:594510927743:android:ea79283352caae70e5ec4a',
    messagingSenderId: '594510927743',
    projectId: 'pdm-app-b7cf2',
    storageBucket: 'pdm-app-b7cf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7tfdAo6t13Ii4JETBWhArCT-E5HO28Go',
    appId: '1:594510927743:ios:734dd04bda1d7092e5ec4a',
    messagingSenderId: '594510927743',
    projectId: 'pdm-app-b7cf2',
    storageBucket: 'pdm-app-b7cf2.appspot.com',
    iosClientId: '594510927743-sv9259b4v4jo8mu674unbrk2cto48tut.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7tfdAo6t13Ii4JETBWhArCT-E5HO28Go',
    appId: '1:594510927743:ios:734dd04bda1d7092e5ec4a',
    messagingSenderId: '594510927743',
    projectId: 'pdm-app-b7cf2',
    storageBucket: 'pdm-app-b7cf2.appspot.com',
    iosClientId: '594510927743-sv9259b4v4jo8mu674unbrk2cto48tut.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGvIzIpLureXu35Gtp_PU8cWZJECJhuRQ',
    appId: '1:594510927743:web:87f6a7dbb8933c4be5ec4a',
    messagingSenderId: '594510927743',
    projectId: 'pdm-app-b7cf2',
    authDomain: 'pdm-app-b7cf2.firebaseapp.com',
    storageBucket: 'pdm-app-b7cf2.appspot.com',
  );

}